name: Run Tests On Push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.10.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.10
#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt
#           echo requirements installed
      - name: Run tests
        run: |
          cd src
          pip install pytest
          pip install pytest-cov
          pytest tests.py